using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System;
using System.Collections.ObjectModel;
using System.Windows.Input;

namespace MapperStudio.ViewModels;

public partial class SetupViewModel : ViewModelBase
{
    private readonly IConnectionService _connectionService;

    [ObservableProperty]
    private string mappingTitle = string.Empty;

    [ObservableProperty]
    private string description = string.Empty;

    [ObservableProperty]
    private ObservableCollection<string> systemTypes = new();

    [ObservableProperty]
    private string? selectedSourceSystem;

    [ObservableProperty]
    private string? selectedTargetSystem;

    [ObservableProperty]
    private ObservableCollection<EntityDefinition> entityOptions = new();

    [ObservableProperty]
    private EntityDefinition? selectedEntity;

    [ObservableProperty]
    private ObservableCollection<ColumnDefinition> targetColumns = new();

    [ObservableProperty]
    private bool isSourceSystemSelected;

    [ObservableProperty]
    private bool isLoadSourceSchemaEnabled;

    [ObservableProperty]
    private bool isLoadTargetSchemaEnabled;

    [ObservableProperty]
    private bool isTargetSystemSelected;

    [ObservableProperty]
    private string sourceStatusTag = "ONLINE";

    [ObservableProperty]
    private string sourceEndpointUrl = "https://api.enterprise.com/v1/users/schema";

    [ObservableProperty]
    private string sourceAuthenticationHeaders = string.Empty;

    [ObservableProperty]
    private ObservableCollection<string> sourceSchemaFields = new();

    [ObservableProperty]
    private ObservableCollection<string> targetSchemaFields = new();

    [ObservableProperty]
    private string targetEndpointUrl = string.Empty;

    [ObservableProperty]
    private string targetAuthenticationHeaders = string.Empty;

    [ObservableProperty]
    private string targetColumnCount = "0 Columns";

    public ICommand NextCommand { get; }
    public ICommand LoadSourceSchemaCommand { get; }
    public ICommand LoadTargetSchemaCommand { get; }

    public SetupViewModel(IConnectionService connectionService)
    {
        _connectionService = connectionService ?? throw new ArgumentNullException(nameof(connectionService));

        NextCommand = new RelayCommand(_ => OnNext(), _ => CanNext());
        LoadSourceSchemaCommand = new RelayCommand(_ => OnLoadSourceSchema(), _ => CanLoadSourceSchema());
        LoadTargetSchemaCommand = new RelayCommand(_ => OnLoadTargetSchema(), _ => CanLoadTargetSchema());

        InitializeSystemTypes();
    }

    private void HandleTargetSystemSelection(string connectionType)
    {
        // Configure endpoint based on connection type
        TargetEndpointUrl = connectionType switch
        {
            "REST API" => "https://api.enterprise.com/v1/target/entities",
            "SOAP" => "https://api.enterprise.com/soap/target?wsdl",
            "Database" => "Server=db.target.com;Database=TargetDB",
            "CSV" => "C:\\data\\target-file.csv",
            "Excel" => "C:\\data\\target-file.xlsx",
            _ => string.Empty
        };

        // Configure authentication headers based on connection type
        TargetAuthenticationHeaders = connectionType switch
        {
            "REST API" => "Bearer token_target_12ab...",
            "SOAP" => "Username: target_admin\nPassword: ****",
            "Database" => "User ID: target_sa\nPassword: ****",
            "CSV" => "N/A",
            "Excel" => "N/A",
            _ => string.Empty
        };
    }

    private void InitializeSystemTypes()
    {
        SystemTypes = new ObservableCollection<string>
        {
            "REST API",
            "SOAP",
            "Database",
            "CSV",
            "Excel"
        };
    }

    // Called when the generated MappingTitle property changes
    partial void OnMappingTitleChanged(string oldValue, string newValue)
    {
        ((RelayCommand)NextCommand).RaiseCanExecuteChanged();
    }

    // Called when SelectedSourceSystem changes (generated by toolkit)
    partial void OnSelectedSourceSystemChanged(string? oldValue, string? newValue)
    {
        IsSourceSystemSelected = !string.IsNullOrEmpty(newValue);
        IsLoadSourceSchemaEnabled = IsSourceSystemSelected;

        if (IsSourceSystemSelected)
        {
            HandleSourceSystemSelection(newValue!);
        }
        else
        {
            ClearSourceConfiguration();
        }

        ((RelayCommand)LoadSourceSchemaCommand).RaiseCanExecuteChanged();
        ((RelayCommand)NextCommand).RaiseCanExecuteChanged();
    }

    // Called when SelectedTargetSystem changes (generated by toolkit)
    partial void OnSelectedTargetSystemChanged(string? oldValue, string? newValue)
    {
        IsLoadTargetSchemaEnabled = !string.IsNullOrEmpty(newValue);
        IsTargetSystemSelected = !string.IsNullOrEmpty(newValue);
        if (IsTargetSystemSelected)
        {
            HandleTargetSystemSelection(newValue!);
        }
        else
        {
            ClearTargetConfiguration();
        }
        ((RelayCommand)LoadTargetSchemaCommand).RaiseCanExecuteChanged();
        ((RelayCommand)NextCommand).RaiseCanExecuteChanged();
    }

    // Called when SelectedEntity changes (generated by toolkit)
    partial void OnSelectedEntityChanged(EntityDefinition? oldValue, EntityDefinition? newValue)
    {
        ((RelayCommand)LoadTargetSchemaCommand).RaiseCanExecuteChanged();
        ((RelayCommand)NextCommand).RaiseCanExecuteChanged();
    }

    private void HandleSourceSystemSelection(string connectionType)
    {
        SourceStatusTag = connectionType switch
        {
            "REST API" => "ONLINE",
            "SOAP" => "ONLINE",
            "Database" => "DATABASE",
            "CSV" => "FILE",
            "Excel" => "FILE",
            _ => "ONLINE"
        };

        // Configure endpoint based on connection type
        SourceEndpointUrl = connectionType switch
        {
            "REST API" => "https://api.enterprise.com/v1/users/schema",
            "SOAP" => "https://api.enterprise.com/soap/service?wsdl",
            "Database" => "Server=db.example.com;Database=YourDB",
            "CSV" => "C:\\data\\source-file.csv",
            "Excel" => "C:\\data\\source-file.xlsx",
            _ => string.Empty
        };

        // Configure authentication headers based on connection type
        SourceAuthenticationHeaders = connectionType switch
        {
            "REST API" => "Bearer token_live_823hdj...\nX-Tenant-ID: US-PROD-01",
            "SOAP" => "Username: admin\nPassword: ****",
            "Database" => "User ID: sa\nPassword: ****",
            "CSV" => "N/A",
            "Excel" => "N/A",
            _ => string.Empty
        };
    }

    private void ClearSourceConfiguration()
    {
        SourceEndpointUrl = string.Empty;
        SourceAuthenticationHeaders = string.Empty;
        SourceSchemaFields.Clear();
        IsLoadSourceSchemaEnabled = false;
    }

    private void ClearTargetConfiguration()
    {
        TargetEndpointUrl = string.Empty;
        TargetAuthenticationHeaders = string.Empty;
        TargetSchemaFields.Clear();
        IsLoadTargetSchemaEnabled = false;
    }

    private void OnLoadSourceSchema()
    {
        if (string.IsNullOrEmpty(SelectedSourceSystem) || string.IsNullOrEmpty(SourceEndpointUrl))
        {
            return;
        }

        try
        {
            // Call your connection service to load schema
            var schema = _connectionService.LoadSourceSchema(SelectedSourceSystem, SourceEndpointUrl) ?? new List<string>();

            SourceSchemaFields.Clear();
            foreach (var field in schema)
            {
                SourceSchemaFields.Add(field);
            }
        }
        catch (Exception ex)
        {
            // Handle error
            System.Diagnostics.Debug.WriteLine($"Error loading source schema: {ex.Message}");
        }
    }

    private bool CanLoadSourceSchema()
    {
        return IsSourceSystemSelected && !string.IsNullOrEmpty(SourceEndpointUrl);
    }

    private void OnLoadTargetSchema()
    {
        if (string.IsNullOrEmpty(SelectedTargetSystem) || SelectedEntity == null)
        {
            return;
        }

        try
        {
            // Call your connection service to load target schema
            var columns = _connectionService.LoadTargetSchema(SelectedTargetSystem, SelectedEntity.Name) ?? new List<ColumnDefinition>();

            TargetColumns.Clear();
            foreach (var column in columns)
            {
                TargetColumns.Add(column);
            }

            TargetColumnCount = $"{TargetColumns.Count} Columns Detected";
            ((RelayCommand)NextCommand).RaiseCanExecuteChanged();
        }
        catch (Exception ex)
        {
            // Handle error
            System.Diagnostics.Debug.WriteLine($"Error loading target schema: {ex.Message}");
        }
    }

    private bool CanLoadTargetSchema()
    {
        return !string.IsNullOrEmpty(SelectedTargetSystem) && SelectedEntity != null;
    }

    private void OnNext()
    {
        if (string.IsNullOrEmpty(MappingTitle) ||
            string.IsNullOrEmpty(SelectedSourceSystem) ||
            string.IsNullOrEmpty(SelectedTargetSystem) ||
            SelectedEntity == null)
        {
            return;
        }

        // Navigate to next step or trigger navigation command
        System.Diagnostics.Debug.WriteLine($"Proceeding with mapping: {MappingTitle}");
    }

    private bool CanNext()
    {
        return !string.IsNullOrEmpty(MappingTitle) &&
               !string.IsNullOrEmpty(SelectedSourceSystem) &&
               !string.IsNullOrEmpty(SelectedTargetSystem) &&
               SelectedEntity != null;
    }
}

public interface IConnectionService
{
    List<string>? LoadSourceSchema(string connectionType, string endpoint);
    List<ColumnDefinition>? LoadTargetSchema(string systemType, string entityName);
}

public class EntityDefinition
{
    public string Name { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
}

public class ColumnDefinition
{
    public string Name { get; set; } = string.Empty;
    public string DataType { get; set; } = string.Empty;
    public bool Required { get; set; }
}
